[package]
name = "weld"
version = "0.1.0"
authors = ["Roy Jacobs <hello@royjacobs.org>"]

[dependencies.weld_core]
path = "../weld-core"

[dependencies.yoga]
git = "https://github.com/bschwind/yoga-rs"
